export const THEME = {
    LOAD: 'THEME_LOAD',
    TOGGLE: 'TOGGLE_THEME',
    LOAD_SUCCESS: 'THEME_LOAD_SUCCESS',
    LOAD_FAIL: 'THEME_LOAD_ERR'
}

export const SESSION = {
    LOAD:'SESSION_LOAD',
    LOAD_SUCCESS: 'SESSION_LOAD_SUCCESS',
    LOAD_FAIL: 'THEME_LOAD_ERR'
}

export const AUTH = {
    LOGIN:'lOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_LOAD_SUCCESS',
    LOGIN_FAIL: 'AUTH_LOAD_ERR'
}

export const SIGNUP = {
    REGISTER:'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_LOAD_SUCCESS',
    REGISTER_FAIL: 'REGISTER_LOAD_ERR'
}

export const PROFILE = {
    ACCESS:'ACCESS_START',
    ACCESS_SUCCESS: 'ACCESS_SUCCESS',
    ACCESS_FAIL: 'ACCESS_ERR'
}
